apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels: # these labels belong to deployment
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: app2
  template: # this is the pod definition
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: joindevops/app2:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: 80 # this port belongs to container
